In [1]:
import pandas as pd

Series

In [2]:
# it is a array like object that can hold any dat type
data=[1,2,3,4,5]
idx=['a','b','c','d','e']
series=pd.Series(data,idx)
print(series)
print(type(series))

a    1
b    2
c    3
d    4
e    5
dtype: int64
<class 'pandas.core.series.Series'>

In [3]:
# for dictionary the key becomes index in Series of panda 
data={
    'a':1,
    'b':3,
    'c':5,
}
series=pd.Series(data)
print(series)
df=pd.DataFrame(data,index=[1])
df

a    1
b    3
c    5
dtype: int64

   a  b  c
1  1  3  5

In [4]:
data=[10,20,30]
index=['a',"apple","cat"]
series=pd.Series(data,index)
print(series)

a        10
apple    20
cat      30
dtype: int64

Dataframe

In [5]:

data={
    "name":["Krishna","sanu","KKB"],
    "age":[23,24,22],
    "city":["Kokata","Midnapore","Jhargram"]
}
df=pd.DataFrame(data)
print(df)

      name  age       city
0  Krishna   23     Kokata
1     sanu   24  Midnapore
2      KKB   22   Jhargram

In [6]:
import numpy as np
a=np.array(data)
b=np.array(df)

print(a)
print(b)

{'name': ['Krishna', 'sanu', 'KKB'], 'age': [23, 24, 22], 'city': ['Kokata', 'Midnapore', 'Jhargram']}
[['Krishna' 23 'Kokata']
 ['sanu' 24 'Midnapore']
 ['KKB' 22 'Jhargram']]

In [7]:
data=[
    {"name":"Krishna","age":32,"city":"Jhargram"},
    {"name":"Sanu","age":22,"city":"Keshiary"},
    {"name":"Sangita","age":29,"city":"Baligeria"},
    {"name":"Krishh","age":21,"city":"Nayagram"}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

      name  age       city
0  Krishna   32   Jhargram
1     Sanu   22   Keshiary
2  Sangita   29  Baligeria
3   Krishh   21   Nayagram
<class 'pandas.core.frame.DataFrame'>

In [8]:
df=pd.read_csv("employees.csv")
df.head(2)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600.0,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600.0,NaN,124,50

In [9]:
df.tail(2)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700.0,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500.0,-,123,50

accessing data from dataframe

In [79]:

data={
    "name":["Krishna","sanu","KKB"],
    "age":[23,24,22],
    "city":["Kokata","Midnapore","Jhargram"]
}
df=pd.DataFrame(data)
df

      name  age       city
0  Krishna   23     Kokata
1     sanu   24  Midnapore
2      KKB   22   Jhargram

In [11]:
df['name']

0    Krishna
1       sanu
2        KKB
Name: name, dtype: object

In [12]:
print(type(df.loc[0]))

<class 'pandas.core.series.Series'>

In [13]:
df.iloc[0]

name    Krishna
age          23
city     Kokata
Name: 0, dtype: object

In [14]:
df.iloc[0,0]

'Krishna'

In [15]:
df.iloc[0,0]

'Krishna'

In [16]:
df

      name  age       city
0  Krishna   23     Kokata
1     sanu   24  Midnapore
2      KKB   22   Jhargram

In [17]:
df['city']

0       Kokata
1    Midnapore
2     Jhargram
Name: city, dtype: object

In [18]:
df.age

0    23
1    24
2    22
Name: age, dtype: int64

In [19]:
df.at[2,"name"]

'KKB'

In [20]:
df.iat[2,0]

'KKB'

In [21]:
df['salary']=[30000,34000,50000]

In [22]:
df

      name  age       city  salary
0  Krishna   23     Kokata   30000
1     sanu   24  Midnapore   34000
2      KKB   22   Jhargram   50000

In [80]:
df['commission']=[2,3.1,1.5]

In [24]:
df

      name  age       city  salary  commission
0  Krishna   23     Kokata   30000         2.0
1     sanu   24  Midnapore   34000         3.1
2      KKB   22   Jhargram   50000         1.5

In [25]:
### to drop a column 
df.drop('commission',axis=1)
### by default the axis value is 0 that represents the rows(vertical)
### the axis value is 0 for rows(vertical ) and 1 for columns(horizontal)
### when axis value is 0 it searches commission in row indexes and doesn't get it & throws error
### it is a temporary operation 
### to make it permanant use "inplace=True"

      name  age       city  salary
0  Krishna   23     Kokata   30000
1     sanu   24  Midnapore   34000
2      KKB   22   Jhargram   50000

In [26]:

df.drop('commission',axis=1,inplace=True)

In [27]:
df

      name  age       city  salary
0  Krishna   23     Kokata   30000
1     sanu   24  Midnapore   34000
2      KKB   22   Jhargram   50000

In [28]:
### to drop a row 
df.drop(0)

   name  age       city  salary
1  sanu   24  Midnapore   34000
2   KKB   22   Jhargram   50000

In [29]:
df

      name  age       city  salary
0  Krishna   23     Kokata   30000
1     sanu   24  Midnapore   34000
2      KKB   22   Jhargram   50000

In [30]:
df.drop(0,inplace=True)

In [31]:
df

   name  age       city  salary
1  sanu   24  Midnapore   34000
2   KKB   22   Jhargram   50000

In [32]:
df.age=df.age+1
### or df['age']=df['age']+1

to manupulate a single data of a single row use df.at or df.iat

In [33]:
df.iat[1,1]=48   # at current 1,1 index
df.at[1,'age']=45  #at the label '1' for row and 'age' for column

In [34]:
df

   name  age       city  salary
1  sanu   45  Midnapore   34000
2   KKB   48   Jhargram   50000

In [35]:
df.head(1)

   name  age       city  salary
1  sanu   45  Midnapore   34000

In [36]:
df.tail(3)

   name  age       city  salary
1  sanu   45  Midnapore   34000
2   KKB   48   Jhargram   50000

In [88]:
df.describe()
df.loc[1]

name               sanu
age                  24
city          Midnapore
commission          3.1
Name: 1, dtype: object

Handling missing values

In [90]:
 #to check wheether there is missing value
df=pd.read_csv("employees.csv")
df.isnull().head(10)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,True,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False

In [39]:
#checks column wise if there is null in any column .for the column has null=> True 
df.isnull().any()

EMPLOYEE_ID       False
FIRST_NAME        False
LAST_NAME         False
EMAIL             False
PHONE_NUMBER      False
HIRE_DATE         False
JOB_ID            False
SALARY             True
COMMISSION_PCT     True
MANAGER_ID        False
DEPARTMENT_ID     False
dtype: bool

In [40]:
#checks row wise --> which row has null=> True 
df.isnull().any(axis=1)

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [ ]:
# to fill the null values 
df_filled=df.fillna("NA")
## fillna replaces all the NaN values with the specified value

In [42]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600.0,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600.0,NaN,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400.0,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000.0,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000.0,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500.0,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000.0,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008.0,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,NaN,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000.0,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000.0,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000.0,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000.0,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,NaN,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800.0,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800.0,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200.0,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008.0,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000.0,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200.0,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700.0,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800.0,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900.0,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000.0,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100.0,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900.0,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800.0,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600.0,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500.0,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000.0,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200.0,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900.0,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500.0,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800.0,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200.0,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700.0,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400.0,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200.0,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300.0,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800.0,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500.0,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100.0,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300.0,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900.0,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400.0,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200.0,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600.0,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200.0,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700.0,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500.0,-,123,50

In [43]:
df_filled

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600.0,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600.0,NA,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400.0,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000.0,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000.0,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500.0,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000.0,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008.0,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,NA,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000.0,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000.0,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000.0,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000.0,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,NA,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800.0,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800.0,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200.0,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008.0,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000.0,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200.0,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700.0,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800.0,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900.0,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000.0,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100.0,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900.0,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800.0,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600.0,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500.0,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000.0,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200.0,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900.0,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500.0,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800.0,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200.0,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700.0,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400.0,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200.0,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300.0,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800.0,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500.0,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100.0,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300.0,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900.0,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400.0,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200.0,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600.0,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200.0,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700.0,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500.0,-,123,50

In [44]:
#to populate the null with the mean of the column //// column-wise
df["SALARY_fillna"]=df["SALARY"].fillna(df["SALARY"].mean())
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,SALARY_fillna
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600.0,-,124,50,2600.0
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600.0,NaN,124,50,2600.0
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400.0,-,101,10,4400.0
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000.0,-,100,20,13000.0
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000.0,-,201,20,6000.0
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500.0,-,101,40,6500.0
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000.0,-,101,70,10000.0
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008.0,-,101,110,12008.0
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,NaN,-,205,110,6142.0
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000.0,-,-,90,24000.0
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000.0,-,100,90,17000.0
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000.0,-,100,90,17000.0
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000.0,-,102,60,9000.0
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,NaN,-,103,60,6142.0
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800.0,-,103,60,4800.0
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800.0,-,103,60,4800.0
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200.0,-,103,60,4200.0
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008.0,-,101,100,12008.0
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000.0,-,108,100,9000.0
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200.0,-,108,100,8200.0
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700.0,-,108,100,7700.0
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800.0,-,108,100,7800.0
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900.0,-,108,100,6900.0
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000.0,-,100,30,11000.0
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100.0,-,114,30,3100.0
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900.0,-,114,30,2900.0
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800.0,-,114,30,2800.0
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600.0,-,114,30,2600.0
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500.0,-,114,30,2500.0
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000.0,-,100,50,8000.0
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200.0,-,100,50,8200.0
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900.0,-,100,50,7900.0
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500.0,-,100,50,6500.0
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800.0,-,100,50,5800.0
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200.0,-,120,50,3200.0
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700.0,-,120,50,2700.0
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400.0,-,120,50,2400.0
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200.0,-,120,50,2200.0
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300.0,-,121,50,3300.0
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800.0,-,121,50,2800.0
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500.0,-,121,50,2500.0
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100.0,-,121,50,2100.0
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300.0,-,122,50,3300.0
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900.0,-,122,50,2900.0
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400.0,-,122,50,2400.0
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200.0,-,122,50,2200.0
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600.0,-,123,50,3600.0
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200.0,-,123,50,3200.0
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700.0,-,123,50,2700.0
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500.0,-,123,50,2500.0

In [45]:
df["SALARY"].mean()

np.float64(6142.0)

In [46]:
df.head(3)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,SALARY_fillna
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600.0,-,124,50,2600.0
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600.0,NaN,124,50,2600.0
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400.0,-,101,10,4400.0

In [47]:
df.head(3).isnull()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,SALARY_fillna
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False

In [92]:
#Renaming columns
df=df.rename(columns={'EMPID':'EMP_ID',"EMAIL":"MAIL"})
df.head(3)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600.0,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600.0,NaN,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400.0,-,101,10

In [49]:
# change the datatype of a column
df["SALARY"]=df["SALARY"].fillna(df["SALARY"].mean()).astype(int)

In [50]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,SALARY_fillna
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50,2600.0
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,NaN,124,50,2600.0
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10,4400.0
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20,13000.0
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20,6000.0
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40,6500.0
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70,10000.0
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110,12008.0
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,6142,-,205,110,6142.0
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90,24000.0
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90,17000.0
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90,17000.0
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60,9000.0
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6142,-,103,60,6142.0
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60,4800.0
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60,4800.0
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60,4200.0
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100,12008.0
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100,9000.0
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100,8200.0
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100,7700.0
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100,7800.0
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100,6900.0
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30,11000.0
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30,3100.0
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30,2900.0
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30,2800.0
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30,2600.0
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30,2500.0
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50,8000.0
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50,8200.0
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50,7900.0
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50,6500.0
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50,5800.0
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50,3200.0
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50,2700.0
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50,2400.0
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50,2200.0
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50,3300.0
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50,2800.0
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50,2500.0
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50,2100.0
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50,3300.0
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50,2900.0
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50,2400.0
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50,2200.0
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50,3600.0
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50,3200.0
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50,2700.0
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50,2500.0

In [51]:
df["new_salary"]=df["SALARY"]*2

The other way to apply a particular function to every element of a column

In [52]:
df["new_salary"]=df["SALARY"].apply(lambda x:x*3)

In [93]:
df.head(3)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600.0,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600.0,NaN,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400.0,-,101,10

In [54]:
#grouping data bassed on values of a particular column
grouped_df=df.groupby("DEPARTMENT_ID")['SALARY'].mean()
print(grouped_df)

DEPARTMENT_ID
10      4400.000000
20      9500.000000
30      4150.000000
40      6500.000000
50      3721.739130
60      5788.400000
70     10000.000000
90     19333.333333
100     8601.333333
110     9075.000000
Name: SALARY, dtype: float64

In [55]:
c=df.groupby("DEPARTMENT_ID",).SALARY.sum()
print(c)
df.head(3)

DEPARTMENT_ID
10      4400
20     19000
30     24900
40      6500
50     85600
60     28942
70     10000
90     58000
100    51608
110    18150
Name: SALARY, dtype: int64

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID,SALARY_fillna,new_salary
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50,2600.0,7800
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,NaN,124,50,2600.0,7800
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10,4400.0,13200

In [56]:
c=df.groupby(["DEPARTMENT_ID","MANAGER_ID"]).SALARY.sum()
print(c)

DEPARTMENT_ID  MANAGER_ID
10             101            4400
20             100           13000
               201            6000
30             100           11000
               114           13900
40             101            6500
50             100           36400
               120           10500
               121           10700
               122           10800
               123           12000
               124            5200
60             102            9000
               103           19942
70             101           10000
90              -            24000
               100           34000
100            101           12008
               108           39600
110            101           12008
               205            6142
Name: SALARY, dtype: int64

In [94]:
#to get the details of a dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     50 non-null     int64
 1   FIRST_NAME      50 non-null     object
 2   LAST_NAME       50 non-null     object
 3   MAIL            50 non-null     object
 4   PHONE_NUMBER    50 non-null     object
 5   HIRE_DATE       50 non-null     object
 6   JOB_ID          50 non-null     object
 7   SALARY          48 non-null     float64
 8   COMMISSION_PCT  49 non-null     object
 9   MANAGER_ID      50 non-null     object
 10  DEPARTMENT_ID   50 non-null     int64
dtypes: float64(1), int64(2), object(8)
memory usage: 4.4+ KB

In [57]:
# multiple aggregate function
agg=df.groupby("DEPARTMENT_ID").SALARY.agg(['mean','sum','count'])
print(agg)

                       mean    sum  count
DEPARTMENT_ID
10              4400.000000   4400      1
20              9500.000000  19000      2
30              4150.000000  24900      6
40              6500.000000   6500      1
50              3721.739130  85600     23
60              5788.400000  28942      5
70             10000.000000  10000      1
90             19333.333333  58000      3
100             8601.333333  51608      6
110             9075.000000  18150      2

Merging dataframes

In [58]:
#it is like join operation of sql database
data1={
    "Key":['a','b','c'],
    "value1":[1,2,3]
}
data2={
    "Key":['a','b','d'],
    "value2":[2,3,4]
}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)
print(df1,"\n",df2)

  Key  value1
0   a       1
1   b       2
2   c       3
   Key  value2
0   a       2
1   b       3
2   d       4

In [59]:
pd.merge(df1,df2,on="Key",how="inner")

  Key  value1  value2
0   a       1       2
1   b       2       3

In [60]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  value1  value2
0   a     1.0     2.0
1   b     2.0     3.0
2   c     3.0     NaN
3   d     NaN     4.0

In [61]:
pd.merge(df1,df2,on="Key",how="left")

  Key  value1  value2
0   a       1     2.0
1   b       2     3.0
2   c       3     NaN

In [62]:
pd.merge(df1,df2,on="Key",how="right")

  Key  value1  value2
0   a     1.0       2
1   b     2.0       3
2   d     NaN       4

Reading Data From Different Sources

In [63]:
import pandas as pd
from io import StringIO
data='{"employee_name":"James","email":"james@gmail.com","job_profile":[{"title1":"Team Lead","title2":"Sr. Developer"}]}'
df=pd.read_json(StringIO(data))
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [64]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [65]:
df.to_json(orient="index")

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [66]:
df.to_json(orient="records")

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [67]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)
df.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [68]:
df.to_csv("wine.csv")

In [69]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\krish\onedrive\desktop\ds&ml\basics\env1\lib\site-packages (6.0.2)

In [70]:
!pip install lxml
# Read HTML tables from a webpage and create a DataFrame
url = "https://www.bankrate.com/banking/list-of-failed-banks/"
tables = pd.read_html(url,match="Days since previous bank failure",header=0)
# tables is a list of DataFrames, let's display the first one
tables[0].head(10)

Requirement already satisfied: lxml in c:\users\krish\onedrive\desktop\ds&ml\basics\env1\lib\site-packages (6.0.2)

  Previous bank failure    Bank failure  Days since previous bank failure
0         June 25, 2004    Feb. 2, 2007                               951
1         Oct. 23, 2020  March 10, 2023                               867
2         Jan. 13, 1945  Sept. 14, 1946                               608
3         Dec. 15, 2017    May 31, 2019                               531
4         Aug. 16, 1996   Nov. 21, 1997                               461
5         Feb. 19, 1962    May 24, 1963                               458
6          May 26, 1953    Aug. 9, 1954                               439

In [71]:
print(type(tables))

<class 'list'>

In [72]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\krish\onedrive\desktop\ds&ml\basics\env1\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\krish\onedrive\desktop\ds&ml\basics\env1\lib\site-packages (from openpyxl) (2.0.0)

In [73]:
xl=pd.read_excel("data.xlsx")
xl.to_pickle("data.pkl")
# --- IGNORE ---
xl.to_pickle("data")

In [74]:

pkl=pd.read_pickle("data.pkl")
pkl

    Name  Age
0  Krish   32
1   John   45
2  Rahul   23